[workspace]
resolver = "2"
members = [
  "apps/desktop/src-tauri", 
  "apps/server",
  "core", 
  "crates/*", 
]

[workspace.package]
version = "0.0.1"
rust-version = "1.72.1"

[workspace.dependencies]
async-trait = "0.1.74"
async-stream = "0.3.5"
bcrypt = "0.15.0"
futures = "0.3.30"
futures-util = "0.3.30"
lettre = { version = "0.11.4", default-features = false, features = [
  "builder",
  "hostname",
  "smtp-transport",
  "tracing",
  "tokio1-rustls-tls",
] }
prisma-client-rust = { git = "https://github.com/Brendonovich/prisma-client-rust.git", tag = "0.6.11", features = [
  "sqlite-create-many",
  "migrations",
  "sqlite",
  "mocking"
], default-features = false }
prisma-client-rust-cli = { git = "https://github.com/Brendonovich/prisma-client-rust.git", tag = "0.6.11", features = [
  "sqlite-create-many",
  "migrations",
  "sqlite",
  "mocking"
], default-features = false }
rand = "0.8.5"
reqwest = { version = "0.11.22", default-features = false, features = [ "json", "rustls-tls" ] }
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
simple_crypt = "0.2.3"
specta = "1.0.5"
tempfile = "3.8.1"
thiserror = "1.0.51"
tokio = { version = "1.35.0", features = [
  # Provides sender/reciever channels
  "sync", 
  # Tells the Tokio runtime to use the multi-thread scheduler.
  "rt-multi-thread",
  # Allows handling shutdown signals (e.g., ctrl+c)
  "signal",
] }
tracing = "0.1.40"
urlencoding = "2.1.3"
